apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ template "dummy-loader.fullname" . }}
  {{- template "chart.labels" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "dummy-loader.fullname" . }}
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 25
